# Where things are
#source:       . # Github Overide's this to [your repo's top level directory]
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes
collections:  null

# Github adds this and can't be overidden
#gist:
# noscript: false

# Handling Reading
#safe:         true # Github Overide's this to true
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Plugins
whitelist: []
gems:
 - jekyll-coffeescript # Included by default from Github
 - jekyll-paginate     # Included by default from Github

# Conversion
markdown:    kramdown # The only markdown processor that github supports anymore.
#highlighter: rouge # Github Overide's this to rouge
#lsi:         false # Github Overide's this to false
excerpt_separator: "\n\n"
#incremental: false # Github Overide's this to false

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null

quiet:    false
defaults: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  input: GFM
  hard_wrap: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style